In [1]:
#behaviors
class Dog:
    def __init__(self, name, size, age, color):
        self.name = name
        self.size = size
        self.age = age
        self.color = color
    def eat(self):
        if self.age <= 1:
            return 'Chicken'
        else:
            return 'Fish'
dog = Dog('Calico', 28, 1, 'White')
dog.eat()

'Chicken'

In [4]:
from abc import ABC, abstractmethod
class Shape(ABC):
    @abstractmethod
    def compute_area(self):
        pass
class Square(Shape):
    def __init__(self, side):
        self.__side = side
    def compute_area(self):
        return self.__side ** 2
square = Square(5)
print(square.compute_area())

25


In [6]:
class Employee:
    def __init__(self, name, salary):
        self._name = name
        self._salary = salary
    def compute_salary(self):
        return self._salary
class Manager(Employee):
    def __init__(self, name, salary, bonus):
        self._name = name
        self._salary = salary
        self.__bonus = bonus
    def compute_salary(self):
        return super().compute_salary() + self.__bonus
mai = Manager('Mai', 100, 50)
salary = mai.compute_salary()
print(salary)

150


In [14]:
class A:
    def __init__(self, num):
        self.num = num
    def show(self):
        print(self.num)
class B(A):
    def show(self):
        print(self.num * self.num)
ins_B = B(3)
ins_B.show()

9


In [ ]:
#Softmax from torch
import torch
import torch.nn as nn
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdim=True)
        return x_exp / total



data = torch.Tensor([1, 2, 3])
my_softmax = MySoftmax()
output = my_softmax(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])


In [33]:
class MyStableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        c = torch.max(x, dim=0)
        x_exp = torch.exp(x - c.values)
        total = x_exp.sum(0, keepdim=True)
        return x_exp / total
data = torch.Tensor([1, 2, 3])
my_stable_softmax = MyStableSoftmax()
output = my_stable_softmax(data)
print(output)

torch.max(data, dim = 0)

tensor([0.0900, 0.2447, 0.6652])


torch.return_types.max(
values=tensor(3.),
indices=tensor(2))

In [52]:
from abc import ABC, abstractmethod
class Person(ABC):
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob
    @abstractmethod
    def describe(self):
        pass
class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade
    def describe(self):
        print(f'{self.name} - {self.yob} - {self.grade:.2f}')
class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject
    def describe(self):
        print(f'{self.name} - {self.yob} - {self.subject}')
class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist
    def describe(self):
        print(f'{self.name} - {self.yob} - {self.specialist}')
student = Student('Peter', 2004, 3.6)
teacher1 = Teacher('Harry', 2000, 'CNTT')
teacher2 = Teacher('Parker', 2002, 'AI')
doctor = Doctor('Alice', 1998, 'Eye')
student.describe()
teacher1.describe()
doctor.describe()


Peter - 2004 - 3.60
Harry - 2000 - CNTT
Alice - 1998 - Eye


In [53]:
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__list_people = list()
    def add_person(self, person: Person):
        self.__list_people.append(person)
    def describe(self):
        print(f'Name: {self.__name}')
        for person in self.__list_people:
            person.describe()
    def count_doctor(self):
        count_doctor = 0
        for person in self.__list_people:
            if isinstance(person, Doctor):
                count_doctor += 1
        return count_doctor
    def sort_age(self):
        self.__list_people.sort(key = lambda x : x.yob)
    def average_teacher_year_of_birth(self):
        olds = []
        for person in self.__list_people:
            if isinstance(person, Teacher):
                olds.append(person.yob)
        return sum(olds) / len(olds)
ward = Ward('Blue Wave:')
ward.add_person(student)
ward.add_person(doctor)
ward.add_person(teacher1)
ward.add_person(teacher2)
ward.describe()
ward.sort_age()
print(ward.count_doctor())
print(ward.average_teacher_year_of_birth())

Name: Blue Wave:
Peter - 2004 - 3.60
Alice - 1998 - Eye
Harry - 2000 - CNTT
Parker - 2002 - AI
1
2001.0


In [72]:
class Stack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__datas = []
    def is_full(self):
        return len(self.__datas) == self.__capacity
    def is_empty(self):
        return len(self.__datas) == 0
    def push(self, value):
        if self.is_full():
            raise Exception("Underflow")
        else:
            self.__datas.append(value)
    def pop(self):
        if self.is_empty():
            raise Exception("Overflow")
        return self.__datas.pop(-1)
    def get_datas(self):
        return self.__datas
stack = Stack(5)
stack.push(2)
stack.push(3)
a = stack.pop()
print(a)

3


In [77]:
class Fruits:
    def __init__(self, price):
        self.price = price
obj = Fruits(50)
obj.quantity = 10
obj.bags = 2
obj.quantity + len(obj.__dict__)
print(obj.__dict__)

{'price': 50, 'quantity': 10, 'bags': 2}


In [ ]:
class Queue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []
    def is_empty(self):
        return len(self.__queue) == 0
    def is_full(self):
        return len(self.__queue) == self.__capacity
    def dequeue(self):
        if self.is_empty():
            raise Exception("Underflow")
        self.__queue.pop(0)
    def enqueue(self, value):
        if self.is_full():
            raise Exception("Overflow")
        self.__queue.append(value)
    def front(self):
        if self.is_empty():
            return 
        return self.__queue[0]
queue = Queue(5)
queue.enqueue(10)
queue.enqueue(20)
print(queue.front())
queue.dequeue()
print(queue.front())


10
20
